In [1]:
import os
import sys
CODE_PATH = "../" # location of frmatch folder from Github
sys.path.insert(0, os.path.abspath(CODE_PATH))
import frmatch
import anndata as ad
import scanpy as sc
import numpy as np
import pandas as pd
import pickle
folder = "../demo_data/"
save = True

Download data here: https://github.com/JCVenterInstitute/celligrate-data/tree/main/AIBS_MTG_data

# Layer1 and MTG

In [2]:
additional_markers = []
nsforest_results = pd.read_pickle(f"{folder}/cluster_membership_results.pkl")
for val in nsforest_results["binary_genes"]: 
    additional_markers.extend(val)
additional_markers = list(np.unique(additional_markers))
print(len(additional_markers), "layer1 binary_genes")

143 layer1 binary_genes

In [3]:
additional_markers = []
nsforest_results = pd.read_pickle(f"{folder}/Clusters_results.pkl")
for val in nsforest_results["binary_genes"]: 
    additional_markers.extend(val)
additional_markers = list(np.unique(additional_markers))
print(len(additional_markers), "mtg binary_genes")

536 mtg binary_genes

In [4]:
additional_markers = []
nsforest_results = pd.read_pickle(f"{folder}/cluster_membership_results.pkl")
for val in nsforest_results["binary_genes"]: 
    additional_markers.extend(val)
nsforest_results = pd.read_pickle(f"{folder}/Clusters_results.pkl")
for val in nsforest_results["binary_genes"]: 
    additional_markers.extend(val)
additional_markers = list(np.unique(additional_markers))
print(len(additional_markers), "union of layer1 and mtg binary_genes")

611 union of layer1 and mtg binary_genes

In [5]:
# Layer1
cluster_header = "cluster_membership"
layer1 = "../../../../../OneDrive - J. CRAIG VENTER INSTITUTE/Documents/frmatch/data"
cell_by_gene = pd.read_csv(f"{layer1}/layer1_cell_by_gene_expression.csv", index_col = 0).T
cluster_labels = pd.read_csv(f"{layer1}/layer1_cell_cluster_labels.csv", index_col = 0)
taxonomy = list(pd.read_csv(f"{layer1}/layer1_taxonomy.csv")["x"])
adata = frmatch.create_frmatch_object_mtx(cell_by_gene, cluster_labels, cluster_header = cluster_header, taxonomy = taxonomy)
adata

AnnData object with n_obs × n_vars = 865 × 16497
    obs: 'cluster_membership'
    uns: 'dendrogram_cluster_membership'

In [6]:
folder = "../demo_data"

In [7]:
# # Running NS-Forest on layer1
# adata = ns.pp.prep_medians(adata, cluster_header)
# adata = ns.pp.prep_binary_scores(adata, cluster_header)
# outputfilename_prefix = cluster_header
# results = nsforesting.NSForest(adata, cluster_header, save = save, save_supplementary = save, 
#                                output_folder = folder, outputfilename_prefix = outputfilename_prefix)
nsforest_results = pd.read_pickle(f"{folder}/cluster_membership_results.pkl")
nsforest_results

,software_version,cluster_header,clusterName,clusterSize,f_score,precision,recall,TN,FP,FN,TP,marker_count,NSForest_markers,binary_genes,onTarget
0,4.1,cluster_membership,e1_e299_SLC17A7_L5b_Cdh13,299,0.961678,0.981550,0.889632,561,5,33,266,2,"[SLC17A7, KIAA1211L]","[SLC17A7, ANKRD33B, LINC00508, SFTA1P, LINC005...",0.491379
1,4.1,cluster_membership,g1_g48_GLI3_Astro_Gja1,48,0.950000,1.000000,0.791667,817,0,10,38,1,[LINC00498],"[LINC00498, EMX2OS, SLC25A18, FGFR3, SLC7A11, ...",0.882322
2,4.1,cluster_membership,g2_g27_APBB1IP_Micro_Ctss,27,0.975610,1.000000,0.888889,838,0,3,24,2,"[ADAM28, CSF2RA]","[ADAM28, CSF2RA, INPP5D, FLI1, PTPRC, PLCG2, C...",0.789460
3,4.1,cluster_membership,g3_g18_GPNMB_OPC_Pdgfra,18,0.862069,1.000000,0.555556,847,0,8,10,2,"[GPNMB, OLIG2]","[GPNMB, OLIG2, STK32A, COL20A1, CSPG4, COL9A1,...",0.656991
4,4.1,cluster_membership,g4_g9_MOG_Oligo_Opalin,9,1.000000,1.000000,1.000000,856,0,0,9,1,[ST18],"[ST18, MOBP, CNDP1, TF, CERCAM, MOG, FOLH1, CD...",0.622487
5,4.1,cluster_membership,i10_i16_TSPAN12_Vip_Mybpc1,16,0.803571,0.900000,0.562500,848,1,7,9,2,"[TSPAN12, CHRNB3]","[TSPAN12, TMC5, LINC01539, FAM46A, CHRNB3, DCN...",0.371987
6,4.1,cluster_membership,i1_i90_COL5A2_Ndnf_Car4,90,0.845324,1.000000,0.522222,775,0,43,47,2,"[COL5A2, TRPC3]","[NMBR, BMP2, COL5A2, TRPC3, PAPSS2, NPNT, BMP6...",0.322911
7,4.1,cluster_membership,i2_i77_LHX6_Sst_Cbln4,77,0.816619,0.838235,0.740260,777,11,20,57,1,[LHX6],"[LHX6, FLT3, TAC1, RSPO3, CALB1, TRBC2, RASGRF...",0.795864
8,4.1,cluster_membership,i3_i56_BAGE2_Ndnf_Cxcl14,56,0.738636,0.866667,0.464286,805,4,30,26,2,"[BAGE2, GREM2]","[BAGE2, SCN5A, GREM2, ARHGAP18, PCDH18, GRB14,...",0.321316
9,4.1,cluster_membership,i4_i54_MC4R_Ndnf_Cxcl14,54,0.857143,0.923077,0.666667,808,3,18,36,2,"[ARHGAP36, ADAM33]","[ARHGAP36, MC4R, COBLL1, LINC01435, HLA_B, ADA...",0.440758
10,4.1,cluster_membership,i5_i47_TRPC3_Ndnf_Car4,47,0.906433,1.000000,0.659574,818,0,16,31,2,"[NTNG1, EYA4]","[KIRREL, SSTR2, TRPC3, NTNG1, TACR1, EYA4, TAR...",0.286741
11,4.1,cluster_membership,i6_i44_GPR149_Vip_Mybpc1,44,0.791667,1.000000,0.431818,821,0,25,19,2,"[FLT1, GPR149]","[FLT1, PLCE1_AS1, PLCE1_AS2, CXCL12, SLC22A3, ...",0.466452
12,4.1,cluster_membership,i7_i31_CLMP_Ndnf_Cxcl14,31,0.900901,1.000000,0.645161,834,0,11,20,2,"[PAX6, TGFBR2]","[FGF10, KIAA1644, CLMP, PAX6, SP8, TGFBR2, WIF...",0.366735
13,4.1,cluster_membership,i8_i27_SNCG_Vip_Mybpc1,27,0.759494,0.923077,0.444444,837,1,15,12,2,"[SNCG, EDNRA]","[SNCG, EDNRA, MMRN2, SCML4, FBN3, TSPAN11, KCN...",0.474188
14,4.1,cluster_membership,i9_i22_TAC3_Vip_Mybpc1,22,0.833333,1.000000,0.500000,843,0,11,11,2,"[BSPRY, IQGAP2]","[BSPRY, MCTP2, OFD1P10Y, IQGAP2, OFD1P9Y, OFD1...",0.547905

In [8]:
# Layer1
if save: save_as = f"{folder}/adata_layer1_R_frmatch.h5ad"
else: save_as = save
adata = frmatch.create_frmatch_object_mtx(cell_by_gene, cluster_labels, nsforest_results = nsforest_results, 
                                          marker_col = "binary_genes", taxonomy = taxonomy, 
                                          additional_markers = additional_markers, save = save_as)
print(len(adata.uns["markers"]))
adata

143

AnnData object with n_obs × n_vars = 865 × 424
    obs: 'cluster_membership'
    uns: 'dendrogram_cluster_membership', 'markers', 'markers_per_cluster'

In [10]:
# MTG
cluster_header = "Clusters"
celligrate = "../../celligrate-data/AIBS_MTG_data"
cell_by_gene = pd.read_csv(f"{celligrate}/cell_by_gene_expression.csv", index_col = 0)
cluster_labels = pd.read_csv(f"{celligrate}/cell_cluster_labels.csv", index_col = 0)
taxonomy = list(pd.read_csv(f"{celligrate}/MTG_taxonomy.csv")["x"])
adata = frmatch.create_frmatch_object_mtx(cell_by_gene, cluster_labels, cluster_header = cluster_header, taxonomy = taxonomy)
adata

AnnData object with n_obs × n_vars = 15603 × 13945
    obs: 'Clusters'
    uns: 'dendrogram_Clusters'

In [11]:
# # Running NS-Forest on layer1
# # This takes a while to run
# adata = ns.pp.prep_medians(adata, cluster_header)
# adata = ns.pp.prep_binary_scores(adata, cluster_header)
# outputfilename_prefix = cluster_header
# results = nsforesting.NSForest(adata, cluster_header, save = save, save_supplementary = save, 
#                                output_folder = folder, outputfilename_prefix = outputfilename_prefix)
nsforest_results = pd.read_pickle(f"{folder}/Clusters_results.pkl")
nsforest_results

,software_version,cluster_header,clusterName,clusterSize,f_score,precision,recall,TN,FP,FN,TP,marker_count,NSForest_markers,binary_genes,onTarget
0,4.1,Clusters,Astro_L1_2_FGFR3_GFAP,61,0.757576,0.961538,0.409836,15541,1,36,25,2,"[ID3, MT1F]","[ID3, GFAP, SERPINI2, WDR49, MT1F, LOC10192839...",0.462900
1,4.1,Clusters,Astro_L1_6_FGFR3_SLC14A1,230,0.863844,0.937888,0.656522,15363,10,79,151,2,"[LOC105376917, RANBP3L]","[LOC105376917, ETNPPL, PRODH, RANBP3L, SLCO1C1...",0.182669
2,4.1,Clusters,Endo_L2_6_NOSTRIN,9,0.862069,1.000000,0.555556,15594,0,4,5,1,[EMCN],"[EPAS1, COL1A2, ANXA3, EMCN, ITIH5, COLEC12, E...",0.246143
3,4.1,Clusters,Exc_L2_3_LINC00507_FREM3,2284,0.770318,0.889666,0.501313,13177,142,1139,1145,2,"[LINC00507, MET]","[ONECUT2, LOC105376496, LINC00507, CNGB1, MET,...",0.135347
4,4.1,Clusters,Exc_L2_4_LINC00507_GLP2R,170,0.555556,0.714286,0.294118,15413,20,120,50,2,"[PENK, LOC105375931]","[GLP2R, PENK, SH3RF2, ACVR1C, MFGE8, LOC105375...",0.106973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,4.1,Clusters,Inh_L5_6_SST_NPM1P10,79,0.598802,0.909091,0.253165,15522,2,59,20,2,"[NPM1P10, ADAMTS20]","[NPM1P10, LOC105371658, LOC105377915, LOC10537...",0.200554
71,4.1,Clusters,Inh_L5_6_SST_TH,27,0.714286,1.000000,0.333333,15576,0,18,9,2,"[TH, LOC102724957]","[TH, LOC102724957, CACNG5, LAYN, KIAA1024, LOC...",0.386145
72,4.1,Clusters,Micro_L1_3_TYROBP,63,0.903084,1.000000,0.650794,15540,0,22,41,2,"[CD74, CSF1R]","[CD74, CX3CR1, FYB, CSF1R, SYK, C3, APBB1IP, L...",0.323362
73,4.1,Clusters,OPC_L1_6_PDGFRA,238,0.863171,0.992647,0.567227,15364,1,103,135,2,"[OLIG1, PDGFRA]","[GPNMB, MROH9, PRRX1, OLIG1, STK32A, PDGFRA, V...",0.259577
74,4.1,Clusters,Oligo_L1_6_OPALIN,313,0.929067,0.979675,0.769968,15285,5,72,241,2,"[CERCAM, ENPP2]","[MOG, CNDP1, CARNS1, LOC101929249, CERCAM, ENP...",0.158644

In [12]:
folder = "../demo_data"

In [13]:
if save: save_as = f"{folder}/adata_MTG_R_frmatch.h5ad"
else: save_as = save
adata = frmatch.create_frmatch_object_mtx(cell_by_gene, cluster_labels, nsforest_results = nsforest_results, 
                                          marker_col = "binary_genes", taxonomy = taxonomy, 
                                          additional_markers = additional_markers, save = save_as)
print(len(adata.uns["markers"]))
adata

536

AnnData object with n_obs × n_vars = 15603 × 598
    obs: 'Clusters'
    uns: 'dendrogram_Clusters', 'markers', 'markers_per_cluster'